# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PluginDeOuf
                                 A QGIS plugin
 C'est le meilleur plugin du monde
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-08
        copyright            : (C) 2022 by Thomas Escrihuela
        email                : thomas.escrihuela@cerema.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PluginDeOuf class from file PluginDeOuf.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .my_plugin import PluginDeOuf
    return PluginDeOuf(iface)
